version: '3'

x-common-variables: &common-variables
  DEBUG: 1
  ENVIRONMENT: DEVELOPMENT

services:
  fastapi-di-api:
    platform: linux/amd64
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    container_name: fastdi-api
    volumes:
      - ../src/:/usr/code/src/
    environment: *common-variables
    ports:
      - 8800:8000
    command: >
      bash -c "
        uvicorn src.api:api --reload --host 0.0.0.0 --port 8000
      "
    depends_on:
      - fastapi-di-db

  fastapi-di-db:
    image: postgres:15.2-alpine
    container_name: fastdi-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    ports:
      - 8832:5432

  fastapi-di-tests:
    platform: linux/amd64
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    container_name: fastdi-tests
    volumes:
      - ../src/:/usr/code/src/
      - ../tests/:/usr/code/tests/
    environment: *common-variables
    command: >
      bash -c "
        pytest tests -x -s -vv
      "
    depends_on:
      - fastapi-di-db

  fastapi-di-migrations:
    platform: linux/amd64
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    container_name: fastdi-migrations
    volumes:
      - ../src/:/usr/code/src/
    environment: *common-variables
    ports:
      - 8800:8000
    working_dir: /usr/code/src
    depends_on:
      - fastapi-di-db

volumes:
  postgres_data: {}
